name: psychological-adv-alstm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7.11
  - pytorch=1.10.2
  - cudatoolkit=11.3
  - ipython=7.31.1
  - numpy=1.21.5
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - pandas=1.3.5
  - freetype=2.10.4
  - ipykernel=6.9.1
  - requests=2.28.1
